name: Daily Supplement Reminder

on:
  schedule:
    - cron: '0 20 * * *'  # 03:00 WIB (hari sebelumnya UTC)
    - cron: '0 23 * * *'  # 06:00 WIB
    - cron: '0 2  * * *'  # 09:00 WIB
    - cron: '0 5  * * *'  # 12:00 WIB
    - cron: '0 8  * * *'  # 15:00 WIB
    - cron: '0 11 * * *'  # 18:00 WIB
    - cron: '0 14 * * *'  # 21:00 WIB
  workflow_dispatch:


jobs:
  run-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run reminder script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
        run: |
          python reminder.py
